apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-gitops-demo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/shaileshraj17/k8s-gitops-demo.git
    targetRevision: main
    path: helm-chart

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true